<?php
  $v = "1.10";

  $debug = isset($_GET["debug"]);
  //$debug = true;

  $defaultUser = $debug ? "fion0210" : "";
  $user = isset($_GET["u"]) ? $_GET["u"] : $defaultUser;
  $source = isset($_GET["source"]) ? $_GET["source"] : "";
  $uid = isset($_SESSION['uid']) ? $_SESSION['uid'] : 0;

  $apiLogo = "http://api2.raidtalk.com.tw/server/getimg.php?sid=%s&type=100";
  $config = array(
      "debug" => $debug,
      "user" => $user,
      "uid" => $uid,
      "apiLogo" =>$apiLogo,
      "apis" => array(

      ),
      "langCode" => "zh-tw",
      "areas" => array(
          "zh-tw" => array("保密不顯示", "澳大利亞", "中國大陸", "加拿大", "美國", "馬來西亞", "日本", "台灣", "香港", "新加坡", "英國"),
          "zh-cn" => array("保密不显示", "澳大利亞", "中国大陆", "加拿大", "美国", "马来西亚", "日本", "台湾", "香港", "新加坡", "英国")
      ),
      "appFiles" => array(
          "android" => "//rcshow.tv/apps/download/getApp.php?type=android&source=$source",
          "ios" => "//rcshow.tv/apps/download/getApp.php?type=ios&source=$source",
          "pc" => "//rcshow.tv/apps/download/"
      )
  );
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>fis3-client</title>
    <meta name="description" content="Mr. Zhang, Packaged web front-end architecture for PC terminals and so on. full vesion.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#157878">
    <?php if ($debug) {?>
    <link rel="stylesheet" type="text/css" href="assets/css/main.min.css?v=<?php echo $v; ?>">
    <?php } else {?>
     <link rel="stylesheet" type="text/css" href="assets/css/main.css?v=<?php echo $v; ?>">
    <?php }?>
</head>

 <body>
    <header>
      <div class="inner">
        <a href="https://zhangli254804018.github.io/fis3-generator-client/">
          <h1>fis3-generator-client</h1>
        </a>
        <h2>Create a fis3 project</h2>
        
          <a href="https://github.com/zhangli254804018/fis3-generator-client" class="button"><small>View project on</small> GitHub</a>
        
        
      </div>
    </header>

    <div id="content-wrapper">
      <div class="inner clearfix">
        <section id="main-content">
          <h1 id="fis3-generator-client">fis3-generator-client</h1>
<p>Create a fis3 project</p>

<ul>
  <li>1、使用項目結構為</li>
</ul>

<div class="highlighter-rouge"><pre class="highlight"><code>        開發過程第一步為
        npm install fis3-generator-client -g
        第二步創建文件夾名稱
        fisc demoApp
</code></pre>
</div>
<p>生成文件結構為</p>

<div class="highlighter-rouge"><pre class="highlight"><code>        依賴包：fis3-client
        參考文件結構為:
                -assets
                        -img
                        -css
                        ……
                js
                        index.js
                        ……
                lib
                        ……
                fis-conf.js
                package.json
                        "fis3-client":"*"
</code></pre>
</div>

<p>但是为了启动单页面 更好的开发 
   我们需要在项目上做以下修改来适应开发。</p>

<div class="highlighter-rouge"><pre class="highlight"><code>        "commander": "2.7.1",
        "mkdirp": "0.5.1",
        "sorted-object": "1.0.0"
</code></pre>
</div>

<ul>
  <li>
    <p>2、后期需要更多的优化兼容开发体验等</p>
  </li>
  <li><a href="https://www.npmjs.com/package/fis3-client">架构源码参考</a></li>
  <li><a href="https://www.npmjs.com/package/fis3-parser-client">核心依賴插件-fis3-parser-client</a></li>
  <li><a href="http://vc.changyou.com/">技術支持</a></li>
</ul>


        </section>

        <aside id="sidebar">
          

          
            <p class="repo-owner"><a href="https://github.com/zhangli254804018/fis3-generator-client">fis3-generator-client</a> is maintained by <a href="https://github.com/zhangli254804018">zhangli254804018</a>.</p>
          

          <p>This page was generated by <a href="https://pages.github.com/">GitHub Pages</a>.</p>
        </aside>
      </div>
    </div>

    
  

</body>
<?php if ($debug) {?>
<script type="text/javascript" src="js/bundle.js?v=<?php echo $v; ?>"></script>
<?php } else {?>
<script type="text/javascript" src="js/main.js?v=<?php echo $v; ?>"></script>
<?php }?>
</html>